language: csharp
sudo: required
dist: trusty
git:
  depth: false
addons:
  sonarcloud:
    organization: "rightnow-ministries"
    token:
      secure: "KeZ3f5tI7UQklL7n6eBL4ZQffxVqA+Vl+ZZ1y4PLRMWAER5gsq96p75574zQiLkRL1hMOTomRlpCF3quQVc3dTNIaZnfXxJJYgaXQUDNXb6r0J3elEQzb549N2hQabSRCfGEbsXSbNabS4jopnHNyEXZ6R0CNFPeo9QFId1iKV4uY2WJkt93z8ypYWRBQiEnCyBWhhKTpj/CxulXdUDCUlUXfGywwHcAtRl0fd6C0iuUzJF5F0tnrAmCGCNukq98q27g2im929/KnlEsubflGL3JFrQ4W2O1aKev16AEa+jWWiS9Z084QFO250y6cEQ258UI0M2f6rdR159+5DrM+rsHEinFGqNKkrdKbwrcZR29wFO3a9qR3TN0IJfg8hhzntNudLLgbYnDeAgZP13lYewVQxHWTXveSUq2f2ecrnTf7G747Qff9kNw+bjJo1vdQNqAOfZtVBi/IdWfa8kJ97NUB9yjL2gvlyZzSNxRCAmlIpDn/EGQ/Sgb7U0eqTTPdu39Rd/rCU42Ln8YcdSE5qM4gUyf8b2GPaRiCrc+73BiT3Ix2bnoSjgXe+p0QyXirnuPoAIZ5jiqdDouukRw2Nw2ORGVoEUQH91ytPtNOHA+IEbjZ9TYTTKmz6FxOCaQplZAyRDlqgOFmxuEy95e6FQIBVV4BCyHintUODsLlwc="
env:
  global:
    # SONAR_LOGIN
    - secure: "YCyDqBl6HOX6HLMlgToZE4CKlrKKcvlla9Xds8UBNNNhZ0VVg7mQ5IPg1Tmn3mh9d2SMdhHtB1v9iGdbTKJmkN0qGGJU14LDXuKCVkC+/ccu6a1vhSRIoCGmb9N7KEHR5IZnOreReuX8ww3SHRLpeXfqwGa7gdeAF4xhqJ7xO6Ms6F+GWkEeu8cfRH7UB9oli0khKhC1NHHrYbgThyLCT5PAu3symPWR+MY4rlWRy24S9tBNZExx7Fentv/y54NAo1k7mvWisyC2a+GndetPkk/l0YuOruZxr/4uvHrrgGOqSuosc7Cf9SV2r6VIbVmUNA2J1ljsNEreVbozUl7quuqcl6/K+Q9k+jZr2omV9s3D0ywMuywp9htpslc4xrWJ3r9q0qVJQkQGrOiCKRLEISiqWaGRdPFsIm6CU1gjKCm6y+nCpSO58N2h1lbFesuModGCUydIxa5ZCSD3xSXnr54QgO4OsNTiuHoihR5t3JDsiI93oJ+tGBYREjMlgk365vd+/Z2KJ8vTvJ+6P90oNqHPcRXhBDkPuXVMqUSKuUOtpGi1mYZluN7kbmob/TzSIa/qah3AdbxNFVLGswH4OtmljVDkaUQBGZ/fppRFTa4ammvgfMrPFYb16B4QzKgWt9HwqYS9nTfU2qpMUdF+W9YPX4ckG1g1QFEVYHZ6TNc="
before_install:
  - dotnet tool install --global dotnet-sonarscanner --version 4.4.2
  - export PATH="$PATH:/home/travis/.dotnet/tools"
solution: ./OrderServiceDemo.sln
mono: none
dotnet: 2.1.403
script:
 - chmod 777 ./*.sh
 - ./build.sh
 - ./sonar.sh
